#debug:
#  true

---
spring:
  application:
    name: @project.name@
  profiles: peer1
eureka:
  instance:
    hostname: eureka-peer1
  client:
    serviceUrl:
      defaultZone: http://eureka-peer2:8762/eureka/
server:
  port: 8761

---
spring:
  application:
    name: @project.name@
  profiles: peer2
eureka:
  instance:
    hostname: eureka-peer2
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka/
server:
  port: 8762

## Standalone Eureka Server
#spring:
#  application:
#    name: @project.name@
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    enableSelfPreservation: false