#debug:
#  true

---
spring:
  application:
    name: @project.name@
  profiles: peer1
eureka:
  instance:
    hostname: eureka-peer1
  client:
    service-url:
      default-zone: http://eureka-peer2:8002/eureka/
server:
  port: 8001

---
spring:
  application:
    name: @project.name@
  profiles: peer2
eureka:
  instance:
    hostname: eureka-peer2
  client:
    service-url:
      default-zone: http://eureka-peer1:8001/eureka/
server:
  port: 8002

#spring:
#  application:
#    name: @project.name@
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/